# Generated by Django 4.1 on 2023-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Spot",
        ),
        migrations.AlterField(
            model_name="place",
            name="img",
            field=models.ImageField(upload_to="pics"),
        ),
    ]
